# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20170429_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsphonemessagerecords',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='smsphonemessagerecords',
            name='senderid',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='smsserviceaudit',
            name='senderid',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
